import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

/**
 * Parse the generated tokens.js into a flat map of { cssVar → resolvedValue }.
 * We read from css-vars.css since it has the canonical --ds-* variable names.
 */
export function readBuiltTokens(buildDir) {
  const cssPath = resolve(buildDir, 'css-vars.css');
  if (!existsSync(cssPath)) return null;

  const css = readFileSync(cssPath, 'utf8');
  const tokens = {};
  // Match lines like:  --ds-semantic-color-text-default: #171717;
  for (const match of css.matchAll(/^\s*(--ds-[\w-]+):\s*(.+?);/gm)) {
    tokens[match[1]] = match[2].trim();
  }
  return tokens;
}

/**
 * Compare previous and current token maps.
 * Returns { added, removed, changed } arrays.
 */
export function diffTokens(prev, curr) {
  const added   = [];
  const removed = [];
  const changed = [];

  const allKeys = new Set([...Object.keys(prev), ...Object.keys(curr)]);

  for (const key of allKeys) {
    if (!(key in prev)) {
      added.push({ cssVar: key, value: curr[key] });
    } else if (!(key in curr)) {
      removed.push({ cssVar: key, value: prev[key] });
    } else if (prev[key] !== curr[key]) {
      changed.push({ cssVar: key, from: prev[key], to: curr[key] });
    }
  }

  return { added, removed, changed };
}

/** Path where the previous snapshot is persisted between builds. */
export function snapshotPath(buildDir) {
  return resolve(buildDir, 'tokens.snapshot.json');
}

export function readSnapshot(buildDir) {
  const p = snapshotPath(buildDir);
  return existsSync(p) ? JSON.parse(readFileSync(p, 'utf8')) : null;
}

export function writeSnapshot(buildDir, tokens) {
  writeFileSync(snapshotPath(buildDir), JSON.stringify(tokens, null, 2), 'utf8');
}

/** Render a human-readable CHANGELOG.md entry for one build. */
export function renderChangelogEntry(diff, date = new Date()) {
  const { added, removed, changed } = diff;
  if (!added.length && !removed.length && !changed.length) return null;

  const iso = date.toISOString().slice(0, 10);
  const lines = [`## ${iso}\n`];

  if (changed.length) {
    lines.push('### Changed\n');
    for (const c of changed) {
      lines.push(`- \`${c.cssVar}\`: \`${c.from}\` → \`${c.to}\``);
    }
    lines.push('');
  }
  if (added.length) {
    lines.push('### Added\n');
    for (const a of added) {
      lines.push(`- \`${a.cssVar}\`: \`${a.value}\``);
    }
    lines.push('');
  }
  if (removed.length) {
    lines.push('### Removed\n');
    for (const r of removed) {
      lines.push(`- \`${r.cssVar}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

const CHANGELOG_HEADER = `# Design Token Changelog
> Auto-generated by \`dsm build\`. Do not edit manually.

`;

/** Prepend a new entry to the changelog file (or create it). */
export function updateChangelog(buildDir, entry) {
  const changelogPath = resolve(buildDir, 'CHANGELOG.md');
  const existing = existsSync(changelogPath)
    ? readFileSync(changelogPath, 'utf8').replace(CHANGELOG_HEADER, '')
    : '';
  writeFileSync(changelogPath, CHANGELOG_HEADER + entry + existing, 'utf8');
  return changelogPath;
}
