import { readFileSync, writeFileSync, existsSync } from 'fs';
import chalk from 'chalk';
import { flattenTokens, resolveReference, loadTokens } from '../utils/tokens.js';
import { enrichComponents } from '../utils/components.js';
import { resolveProjectPaths } from '../utils/paths.js';

function buildSemanticColorTable(flat) {
  return Object.entries(flat)
    .filter(([k]) => k.startsWith('semantic.color.'))
    .map(([path, token]) => {
      const shortPath = path.replace('semantic.color.', '');
      const rawValue  = token.$value;
      const resolved  = typeof rawValue === 'string' && rawValue.startsWith('{')
        ? resolveReference(rawValue, flat)
        : rawValue;
      return { path: shortPath, cssVar: `--ds-${path.replace(/\./g, '-')}`, value: resolved, desc: token.$description ?? '' };
    });
}

function buildComponentList(components) {
  return enrichComponents(components).map(c => ({
    name: c.name,
    level: c.levelLabel,
    path: c.path,
    description: c.description,
    variants: c.variants?.join(', ') ?? 'n/a',
    sizes: c.sizes?.join(', ') ?? 'n/a',
    contains: c.contains?.join(', ') ?? 'none',
    required: Object.entries(c.props ?? {})
      .filter(([, v]) => v.required)
      .map(([k]) => k)
      .join(', ') || 'none',
  }));
}

/** Splice (or create) the DSM section in a file. Idempotent. */
function spliceDsmSection(filePath, content) {
  const SECTION_START = '<!-- DSM:START -->';
  const SECTION_END   = '<!-- DSM:END -->';
  const block = `${SECTION_START}\n${content}\n${SECTION_END}`;

  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, 'utf8');
    if (existing.includes(SECTION_START)) {
      const before = existing.substring(0, existing.indexOf(SECTION_START));
      const after  = existing.substring(existing.indexOf(SECTION_END) + SECTION_END.length);
      return before + block + after;
    }
    return existing.trimEnd() + '\n\n' + block + '\n';
  }
  return block + '\n';
}

export async function generateContextCommand() {
  console.log(chalk.cyan('\n📝 Generating context files...\n'));

  const { tokensPath, componentsPath, dsRoot, claudePath, agentsPath } = resolveProjectPaths();

  if (!existsSync(tokensPath)) {
    console.error(chalk.red('✗ design-system/tokens.json not found. Run `dsm init` first.\n'));
    process.exit(1);
  }

  const tokens    = JSON.parse(readFileSync(tokensPath, 'utf8'));
  const registry  = existsSync(componentsPath)
    ? JSON.parse(readFileSync(componentsPath, 'utf8'))
    : { components: [] };

  const flat       = flattenTokens(tokens);
  const semColors  = buildSemanticColorTable(flat);
  const components = buildComponentList(registry.components ?? []);

  // ── context.md (full reference, unchanged) ───────────────────────────────
  const contextMd   = generateContextMd(flat, semColors, components);
  const contextPath = `${dsRoot}/context.md`;
  writeFileSync(contextPath, contextMd, 'utf8');
  console.log(chalk.green('  ✓') + '  design-system/context.md');

  // ── CLAUDE.md (Claude Code — slim rules + CLI hints) ─────────────────────
  writeFileSync(claudePath, spliceDsmSection(claudePath, generateClaudeMd()), 'utf8');
  console.log(chalk.green('  ✓') + '  CLAUDE.md');

  // ── AGENTS.md (Codex — same rules, Codex-flavoured hints) ────────────────
  writeFileSync(agentsPath, spliceDsmSection(agentsPath, generateAgentsMd()), 'utf8');
  console.log(chalk.green('  ✓') + '  AGENTS.md');

  console.log(chalk.green('\n✓ Context generation complete.\n'));
}

// ─────────────────────────────────────────────────────────────────────────────

function generateClaudeMd() {
  return `# Design System Guidelines
> Auto-generated by dsm generate-context. Do not edit manually.
> Full token reference: \`design-system/context.md\`

## ⚠️ CRITICAL RULES — ALWAYS FOLLOW

1. **NEVER use raw CSS values** — no hex colors, no \`rgb()\`, no hardcoded \`px\` values in inline styles.
2. **ALWAYS use semantic CSS variables** from \`design-system/build/css-vars.css\` or Tailwind token classes.
3. **ALWAYS use components from the registry** before creating a new one. Run \`dsm list-components\` to check.
4. **NEVER create a duplicate component** — if a component with \`"doNotCreate": true\` exists, use it.
5. **After adding a new component**, register it in \`design-system/components.json\` and run \`dsm generate-context\`.
6. **Import tokens** in your Tailwind config via \`design-system/build/tailwind.tokens.cjs\`.

---

## Token Naming Convention

\`\`\`text
--ds-{layer}-{category}-{intent}-{modifier}

Examples:
  --ds-semantic-color-text-default
  --ds-semantic-color-background-subtle
  --ds-component-button-height-md
  --ds-primitive-color-brand-500
\`\`\`

---

## CLI — Token & Component Lookups

Look up a token (partial name, full path, or CSS variable):
\`\`\`bash
dsm get-token text-default
dsm get-token --ds-semantic-color-border-focus
dsm get-token background --json
\`\`\`

List components (optional filter):
\`\`\`bash
dsm list-components
dsm list-components --filter Button --json
\`\`\`

Validate for violations:
\`\`\`bash
dsm validate [path]
\`\`\`

Full token reference: \`design-system/context.md\`

---

## Claude Code Commands

- \`/tokenize\` — replace hardcoded values in a file with token CSS variables
- \`/new-component\` — scaffold a new component that follows the design system
- \`/audit-component\` — check a component for design system violations
`;
}

function generateAgentsMd() {
  return `# Design System Guidelines
> Auto-generated by dsm generate-context. Do not edit manually.
> Full token reference: \`design-system/context.md\`

## ⚠️ CRITICAL RULES — ALWAYS FOLLOW

1. **NEVER use raw CSS values** — no hex colors, no \`rgb()\`, no hardcoded \`px\` values in inline styles.
2. **ALWAYS use semantic CSS variables** from \`design-system/build/css-vars.css\` or Tailwind token classes.
3. **ALWAYS use components from the registry** before creating a new one. Run \`dsm list-components\` to check.
4. **NEVER create a duplicate component** — if a component with \`"doNotCreate": true\` exists, use it.
5. **After adding a new component**, register it in \`design-system/components.json\` and run \`dsm generate-context\`.
6. **Import tokens** in your Tailwind config via \`design-system/build/tailwind.tokens.cjs\`.

---

## Token Naming Convention

\`\`\`text
--ds-{layer}-{category}-{intent}-{modifier}

Examples:
  --ds-semantic-color-text-default
  --ds-semantic-color-background-subtle
  --ds-component-button-height-md
  --ds-primitive-color-brand-500
\`\`\`

---

## CLI — Token & Component Lookups

Look up a token (partial name, full path, or CSS variable):
\`\`\`bash
dsm get-token text-default
dsm get-token --ds-semantic-color-border-focus
dsm get-token background --json
\`\`\`

List components (optional filter):
\`\`\`bash
dsm list-components
dsm list-components --filter Button --json
\`\`\`

Validate for violations:
\`\`\`bash
dsm validate [path]
\`\`\`

Full token reference: \`design-system/context.md\`

---

## Codex Commands

Use shell tool to run any \`dsm\` command above. The CLI is the primary interface.
- Scan + auto-report: \`dsm validate [path] --json\`
- Full reference: \`cat design-system/context.md\`
`;
}

function generateContextMd(flat, semColors, components) {
  const primitiveColors = Object.entries(flat)
    .filter(([k]) => k.startsWith('primitive.color.') && !k.includes('white') && !k.includes('black'))
    .map(([path, token]) => `| \`${path}\` | \`${token.$value}\` |`)
    .join('\n');

  const spacingRows = Object.entries(flat)
    .filter(([k]) => k.startsWith('primitive.spacing.'))
    .map(([path, token]) => `| \`${path}\` | \`${token.$value}\` |`)
    .join('\n');

  const componentTokenRows = Object.entries(flat)
    .filter(([k]) => k.startsWith('component.'))
    .map(([path, token]) => {
      const val = typeof token.$value === 'string' && token.$value.startsWith('{')
        ? `${token.$value} → ${resolveReference(token.$value, flat)}`
        : token.$value;
      return `| \`${path}\` | \`${val}\` |`;
    })
    .join('\n');

  return `# Design System Token Reference
> Auto-generated by dsm generate-context.

## Semantic Colors

| Token Path | Resolved Value | Description |
|---|---|---|
${semColors.map(c => `| \`semantic.color.${c.path}\` | \`${c.value}\` | ${c.desc} |`).join('\n')}

---

## Primitive Colors

| Token Path | Value |
|---|---|
${primitiveColors}

---

## Spacing Scale

| Token Path | Value |
|---|---|
${spacingRows}

---

## Component Tokens

| Token Path | Value |
|---|---|
${componentTokenRows}

---

## Components

${components.map(c => `### ${c.name}\n- **Level:** ${c.level}\n- **File:** \`${c.path}\`\n- **Description:** ${c.description}\n- **Variants:** ${c.variants}\n- **Sizes:** ${c.sizes}\n- **Contains:** ${c.contains}\n- **Required props:** ${c.required}`).join('\n\n')}
`;
}
