import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Custom formatter: outputs a CJS module with token values
 * organized for direct use in tailwind.config.js `theme.extend`.
 *
 * Style Dictionary v4 (DTCG mode) exposes tokens with:
 *   token.$value  — the resolved value
 *   token.$type   — the token type
 *   token.key     — full dotted path in braces, e.g. "{primitive.color.brand.500}"
 */
function tailwindFormatter({ dictionary }) {
  const colors    = {};
  const spacing   = {};
  const fontSize  = {};
  const fontWeight = {};
  const lineHeight = {};
  const letterSpacing = {};
  const borderRadius = {};
  const boxShadow  = {};
  const fontFamily = {};
  const opacity   = {};

  // Helper: derive kebab-case CSS variable name from a token key
  // e.g. "{semantic.color.text.default}" → "--ds-semantic-color-text-default"
  function toCssVar(key) {
    const path = key.replace(/^\{|\}$/g, '').replace(/\./g, '-');
    return `var(--ds-${path})`;
  }

  for (const token of dictionary.allTokens) {
    // SD v4 DTCG: use $value and key
    const value = token.$value ?? token.value;
    const rawKey = token.key ?? '';
    const path = rawKey.replace(/^\{|\}$/g, '').split('.');
    const layer = path[0];

    if (layer === 'primitive') {
      const category = path[1];
      if (category === 'color') {
        // e.g. primitive.color.brand.500 → colors['brand']['500']
        const [, , group, ...rest] = path;
        if (!group) continue;
        if (!colors[group]) colors[group] = {};
        if (rest.length === 0) {
          colors[group] = value;
        } else {
          colors[group][rest.join('-')] = value;
        }
      }
      if (category === 'spacing') {
        const k = path[2].replace('-', '.'); // '0-5' → '0.5'
        spacing[k] = value;
      }
      if (category === 'typography') {
        const subcat = path[2];
        const k      = path[3];
        if (subcat === 'fontSize')      fontSize[k]      = value;
        if (subcat === 'fontWeight')    fontWeight[k]    = String(value);
        if (subcat === 'lineHeight')    lineHeight[k]    = String(value);
        if (subcat === 'letterSpacing') letterSpacing[k] = value;
        if (subcat === 'fontFamily')    fontFamily[k]    = value;
      }
      if (category === 'borderRadius') {
        const k = path[2];
        borderRadius[k === 'default' ? 'DEFAULT' : k] = value;
      }
      if (category === 'shadow') {
        const key = path[2];
        boxShadow[key === 'default' ? 'DEFAULT' : key] = value;
      }
      if (category === 'opacity') {
        opacity[path[2]] = value;
      }
    }

    // Semantic colors as CSS-variable references for Tailwind
    // e.g. semantic.color.text.default → colors['ds-text-default'] = 'var(--ds-semantic-color-text-default)'
    if (layer === 'semantic' && path[1] === 'color') {
      const twKey  = path.slice(2).join('-');           // text-default, background-subtle
      const cssVar = toCssVar(rawKey);                  // var(--ds-semantic-color-text-default)
      colors[`ds-${twKey}`] = cssVar;
    }
  }

  return `/* Auto-generated by dsm build. Do not edit manually. */
/* Usage: const dsTokens = require('./design-system/build/tailwind.tokens.cjs')  */
/*        then spread into tailwind.config.js theme.extend                       */

module.exports = {
  colors: ${JSON.stringify(colors, null, 2)},
  spacing: ${JSON.stringify(spacing, null, 2)},
  fontSize: ${JSON.stringify(fontSize, null, 2)},
  fontWeight: ${JSON.stringify(fontWeight, null, 2)},
  lineHeight: ${JSON.stringify(lineHeight, null, 2)},
  letterSpacing: ${JSON.stringify(letterSpacing, null, 2)},
  borderRadius: ${JSON.stringify(borderRadius, null, 2)},
  boxShadow: ${JSON.stringify(boxShadow, null, 2)},
  fontFamily: ${JSON.stringify(fontFamily, null, 2)},
  opacity: ${JSON.stringify(opacity, null, 2)},
};
`;
}

export default {
  // Source: single DTCG tokens file
  source: [resolve(__dirname, 'tokens.json')],

  // Tell Style Dictionary this is W3C DTCG format
  preprocessors: ['tokens-studio'],

  platforms: {
    // ── 1. CSS Custom Properties ────────────────────────────────────────────
    css: {
      transformGroup: 'css',
      prefix: 'ds',
      buildPath: resolve(__dirname, 'build') + '/',
      files: [
        {
          destination: 'css-vars.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: true,
          },
        },
      ],
    },

    // ── 2. ES Module (raw token values) ────────────────────────────────────
    js: {
      transformGroup: 'js',
      buildPath: resolve(__dirname, 'build') + '/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },

    // ── 3. Tailwind Config Extension ───────────────────────────────────────
    tailwind: {
      transformGroup: 'js',
      buildPath: resolve(__dirname, 'build') + '/',
      files: [
        {
          destination: 'tailwind.tokens.cjs',
          format: 'custom/tailwind',
        },
      ],
    },
  },
};

// Register custom Tailwind format
// (Style Dictionary v4 requires registering via the SD instance,
//  so we export a setup function that build.js calls before buildAllPlatforms)
export function registerFormats(sd) {
  sd.registerFormat({
    name: 'custom/tailwind',
    format: tailwindFormatter,
  });
}
